-- Productos que Ceven le asigna a un proyecto del pipeline REGI (Deal
-- Registration de HP/Poly). Ver docs/HISTORIAL.md (25/08/2026, "Editar
-- proyectos REGI + asignar productos") para el porqué.
--
-- poly_regi_pipeline.amount es el monto que REPORTA el archivo de HP; esta
-- tabla es la sumatoria PROPIA de Ceven, armada eligiendo productos reales
-- del catálogo de Poly (mismos SKU/precios que el cotizador). Los dos montos
-- se mantienen separados a propósito y conviven como KPI — no hay forma de
-- saber cuál "gana", así que no se pisan entre sí.
--
-- Hija de poly_regi_pipeline por `opd` con ON DELETE CASCADE: si una
-- oportunidad sale del Excel en una reimportación (ya no viene en el
-- archivo), sus productos asignados dejan de tener proyecto y se van con
-- ella — mismo criterio de "reemplazo, no acumulación" que ya rige la tabla
-- padre (20260825120000_poly_regi_pipeline.sql).
create table public.poly_regi_pipeline_productos (
  id bigint generated by default as identity primary key,
  opd text not null references public.poly_regi_pipeline(opd) on delete cascade,
  sku text not null,
  descripcion text not null default '',
  cantidad numeric not null default 1,
  precio_unitario numeric not null default 0,
  created_at timestamptz not null default now(),
  created_by text
);
comment on table public.poly_regi_pipeline_productos is
  'Productos que Ceven asigna a un proyecto del pipeline REGI (poly_regi_pipeline), elegidos del catálogo de Poly. Sumatoria propia, distinta del monto que reporta el archivo de HP — las dos conviven como KPI. Se borra en cascada cuando el proyecto (opd) sale de una reimportación del Excel.';

create index poly_regi_pipeline_productos_opd_idx on public.poly_regi_pipeline_productos (opd);

-- ── RLS ─────────────────────────────────────────────────────────────────
-- Mismo criterio que la tabla padre: dato de negocio común entre el staff,
-- sin Edge Function ni función security definer nueva.

alter table public.poly_regi_pipeline_productos enable row level security;

create policy poly_regi_pipeline_productos_select on public.poly_regi_pipeline_productos
  for select to authenticated using (public.ceven_is_staff());
create policy poly_regi_pipeline_productos_insert on public.poly_regi_pipeline_productos
  for insert to authenticated with check (public.ceven_is_writer());
create policy poly_regi_pipeline_productos_update on public.poly_regi_pipeline_productos
  for update to authenticated using (public.ceven_is_writer()) with check (public.ceven_is_writer());
create policy poly_regi_pipeline_productos_delete on public.poly_regi_pipeline_productos
  for delete to authenticated using (public.ceven_is_writer());
